### PR TITLE
Update to EDSDK 13.12.10

### PR DESCRIPTION
**Pull request by brinoausrino**
Updated to the most recent EDSDK. The only code I needed to update refers to camera properties in utils.cpp since Canon added some new and removed other ones

### CODE REVIEW

**Comment by elliotwoods** [comment]
Hey! I didn’t merge this right away because you removed ofxAddonLib pattern and the previous comments from the read me about tested platforms (and about using ofxAddonLib)

**Comment by brinoausrino** [comment]
Ok, I readded the ofxAddonLib comment. Since you could now also use the project generator to include the addon in the project might be the more standard of approach?

**Comment by elliotwoods** [comment]
Ah cool - you got it working with more recent version than me
I'd like to pull this. I'll roll back the readme edit (removing ofxAddonLib)
Everything ok to pull?

**Comment by brinoausrino** [comment]
Yes, I think so.

-------

Today I made some changes on the Initializer class, since I got problems with the M50 disconnecting all ~5min. I needed to restart the SDK though to find the device again (I'm not sure if my changes will cause conflicts when using multiple cameras)

**Comment by elliotwoods** [comment]
@brinoausrino - i've moved the `init()` call that you added to the `X()` access into the constructor of `Initializer`
i.e. the behaviour is that the first time you 'get' the initializer it will init
From there if you want a deinit+reinit then you should call `X().init()` manually yourself

Having the `EdsTerminateSDK` called every time you access `X()` was messing with my other applications so i moved it out.
Just a heads up that you might want to add that `init()` manually in your own code somewhere

**Pull request merged**
